/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_product/models/spray_bottle.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/spray_bottle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.spray_nogal_back.geometry} material={materials['Material.001']} position={[-0.313, 5.033, -0.001]} scale={[0.547, 0.547, 0.177]} />
      <mesh geometry={nodes.spray_handle.geometry} material={materials['Material.002']} position={[-0.74, 4.299, 0.072]} rotation={[Math.PI / 2, -0.423, 0]} scale={[0.115, 0.186, 0.186]} />
      <mesh geometry={nodes.spray_nogel.geometry} material={materials['Material.004']} position={[-0.875, 4.901, -0.001]} rotation={[0, 0, -Math.PI / 2]} scale={[0.143, 0.135, 0.176]} />
      <mesh geometry={nodes.cap.geometry} material={materials['Material.003']} position={[0.017, 4.038, 0]} scale={0.313} />
      <mesh geometry={nodes.bottle.geometry} material={materials.Material} position={[0.017, 2.07, 0]} scale={[0.62, 1.241, 0.62]} />
      <mesh geometry={nodes.label.geometry} material={materials['Material.005']} position={[0.017, 0.608, 0]} scale={0.637} />
      <mesh geometry={nodes.logo.geometry} material={nodes.logo.material} position={[0.281, 1.992, 1.155]} rotation={[Math.PI / 2, 0, 0]} scale={0.755} />
    </group>
  )
}

useGLTF.preload('/spray_bottle.glb')
