/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_product/models/bottle.glb 
*/

import {useRef, useMemo, useEffect} from 'react'
import { useGLTF } from '@react-three/drei'
import { useBodyMaterial } from '@/shared/useBodyMaterial';
import CylindricalLogoDecal from '@/shared/CylindricalLogoDecal';
import * as THREE from 'three'

const MODEL_PATH = '/3d_product/models/bottle.glb';

export function Bottle({
  bodyColor,
  capColor,
  singleColorMode,
  labelImage,
  logoImage,
  brandText,
  labelVisible = true,
  logoVisible = true,
  logoX = 0,
  logoY = 0,
  logoRotation = 0,
  cylindricalLabel = true, 
  logoScale, 
  scale = 0.5,
  ...props}) {
  const { nodes, materials } = useGLTF(MODEL_PATH)

  const labelRef = useRef()
    const bodyRef = useRef()
  
    const bodyMaterial = useBodyMaterial(bodyColor)
    const capMaterial = useBodyMaterial(capColor);
  
    const labelMaterial = useMemo(() => {
      const mat = nodes.Cylinder.material.clone()
      mat.transparent = true
      mat.side = THREE.DoubleSide
      mat.depthWrite = false
      mat.needsUpdate = true
      mat.opacity = 1.0
      return mat
    }, [materials])
  
    useEffect(() => {
      if (labelImage && labelRef.current) {
        const loader = new THREE.TextureLoader()
        loader.load(labelImage, (texture) => {
          texture.colorSpace = THREE.SRGBColorSpace
          texture.flipY = false
          texture.wrapS = texture.wrapT = THREE.RepeatWrapping
          texture.repeat.set(1, 2)
          texture.offset.set(0, 0)
          texture.needsUpdate = true
  
          const customMaterial = new THREE.MeshBasicMaterial({
            map: texture,
            transparent: true,
            side: THREE.DoubleSide,
            depthWrite: true,
          })
          if (labelRef.current) labelRef.current.material = customMaterial
        })
      } else if (labelRef.current) {
        labelRef.current.material = labelMaterial
      }
    }, [labelImage, labelMaterial])

  return (
    <group {...props} dispose={null}>
      <mesh ref={bodyRef} geometry={nodes.Cylinder.geometry} material={bodyMaterial} position={[0, 1.923, 0]} scale={[0.709, 1.244, 0.709]} />
      <mesh geometry={nodes.caps.geometry} material={singleColorMode ? bodyMaterial : capMaterial} position={[0.001, 4.727, 0]} scale={[-0.3, -0.19, -0.3]} />
      {/* <mesh geometry={nodes.label.geometry} material={nodes.label.material} position={[0, 1.42, 0]} scale={0.726} /> */}

      {labelVisible && (
        <mesh ref={labelRef} geometry={nodes.label.geometry} material={nodes.label.material} position={[0, 1.42, 0]} scale={0.726}>
          {logoVisible && logoImage && (
            <CylindricalLogoDecal
              textureUrl={logoImage}
              labelWidth={1.3}
              labelHeight={1.3}
              labelCircumference={2.77}
              x={logoX}
              y={logoY}
              rotationY={logoRotation}
              cylindrical={cylindricalLabel}
              scale={logoScale}
            />
          )}
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
