/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_product/models/container.glb 
*/

import {useRef, useMemo, useEffect} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useBodyMaterial } from '@/shared/useBodyMaterial';
import SimpleLogoDecal from '@/shared/SimpleLogoDecal';

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

const MODEL_PATH = `${basePath}/3d_product/models/container.glb`;

export function Container({
  bodyColor,
  capColor,
  singleColorMode,
  labelImage,
  logoImage,
  brandText,
  labelVisible = true,
  logoVisible = true,
  logoX = 0,
  logoY = 0,
  logoRotation = 0,
  cylindricalLabel = true, 
  logoScale, 
  scale = 0.5,
  ...props}) {
  const { nodes, materials } = useGLTF(MODEL_PATH)
  const labelRef = useRef()
  const bodyRef = useRef()

  const bodyMaterial = useBodyMaterial(bodyColor);
  const capMaterial = useBodyMaterial(capColor);


  const labelMaterial = useMemo(() => {
    const mat = nodes.label.material.clone()
    mat.transparent = true
    mat.side = THREE.DoubleSide
    mat.depthWrite = false
    mat.needsUpdate = true
    mat.opacity = 1.0
    return mat
  }, [materials])


  useEffect(() => {
    if (labelImage && labelRef.current) {
      const loader = new THREE.TextureLoader()
      loader.load(labelImage, (texture) => {
        texture.colorSpace = THREE.SRGBColorSpace
        texture.flipY = false
        texture.wrapS = texture.wrapT = THREE.RepeatWrapping
        texture.repeat.set(1, 1)
        texture.offset.set(0, 0)
        texture.needsUpdate = true

        const customMaterial = new THREE.MeshBasicMaterial({
          map: texture,
          transparent: true,
          side: THREE.DoubleSide,
          depthWrite: true,
        })
        if (labelRef.current) labelRef.current.material = customMaterial
      })
    } else if (labelRef.current) {
      labelRef.current.material = labelMaterial
    }
  }, [labelImage, labelMaterial])

  return (
    <group {...props} dispose={null}>
      <mesh ref={bodyRef} geometry={nodes.Cube.geometry} material={bodyMaterial} position={[0, 2.351, 0]} scale={[1.854, 2.305, 1.422]} />
      <mesh geometry={nodes.caps.geometry} material={singleColorMode ? bodyMaterial : capMaterial} position={[-1.409, 4.158, 0.124]} scale={[-0.389, -0.142, -0.389]} />
      {/* <mesh geometry={nodes.label.geometry} material={nodes.label.material} position={[0, 2.291, 1.497]} rotation={[Math.PI / 2, 0, 0]} scale={1.715} /> */}

      {labelVisible && (
        <mesh ref={labelRef} geometry={nodes.label.geometry} material={nodes.label.material} position={[0, 2.291, 1.497]} rotation={[Math.PI / 2, 0, 0]} scale={1.715}>
          {logoVisible && logoImage && (
            <SimpleLogoDecal
                textureUrl={logoImage}
                x={logoX}           // [-0.5, 0.5]
                y={logoY}           // [-0.5, 0.5]
                rotationZ={logoRotation}
                scale={logoScale}
            />
          )}
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
