/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_product/models/kanster.glb 
*/

import {useMemo, useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useBodyMaterial } from '@/shared/useBodyMaterial';
import CylindricalLogoDecal from '@/shared/CylindricalLogoDecal';
import * as THREE from 'three'

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

const MODEL_PATH = `${basePath}/3d_product/models/kanster.glb`;

export function Kanster({
  bodyColor,
  capColor,
  singleColorMode,
  labelImage,
  logoImage,
  brandText,
  labelVisible = true,
  logoVisible = true,
  logoX = 0,
  logoY = 0,
  logoRotation = 0,
  cylindricalLabel = true, 
  logoScale, 
  scale = 0.5,
  ...props}) {
  const { nodes, materials } = useGLTF(MODEL_PATH)

  const labelRef = useRef()
  const bodyRef = useRef()

  const bodyMaterial = useBodyMaterial(bodyColor);
  const capMaterial = useBodyMaterial(capColor);


  const labelMaterial = useMemo(() => {
    const mat = nodes.body.material.clone()
    mat.transparent = true
    mat.side = THREE.DoubleSide
    mat.depthWrite = false
    mat.needsUpdate = true
    mat.opacity = 1.0
    return mat
  }, [materials])

  useEffect(() => {
    if (labelImage && labelRef.current) {
      const loader = new THREE.TextureLoader()
      loader.load(labelImage, (texture) => {
        texture.colorSpace = THREE.SRGBColorSpace
        texture.flipY = false
        texture.wrapS = texture.wrapT = THREE.RepeatWrapping
        texture.repeat.set(1, 2)
        texture.offset.set(0, 0)
        texture.needsUpdate = true

        const customMaterial = new THREE.MeshBasicMaterial({
          map: texture,
          transparent: true,
          side: THREE.DoubleSide,
          depthWrite: true,
        })
        if (labelRef.current) labelRef.current.material = customMaterial
      })
    } else if (labelRef.current) {
      labelRef.current.material = labelMaterial
    }
  }, [labelImage, labelMaterial])

  return (
    <group {...props} dispose={null}>
      <mesh ref={bodyRef} geometry={nodes.body.geometry} material={bodyMaterial} position={[0.073, 1.935, 0]} scale={1.342} />
      <mesh geometry={nodes.caps.geometry} material={singleColorMode ? bodyMaterial : capMaterial} position={[0.083, 4.36, -0.006]} scale={[1.332, 0.391, 1.332]} />
      {/* <mesh geometry={nodes.label.geometry} material={nodes.label.material} position={[0.072, 2.093, -0.032]} scale={[1.365, 1.472, 1.397]} /> */}

      {labelVisible && (
        <mesh ref={labelRef} geometry={nodes.label.geometry} material={nodes.label.material} position={[0.072, 2.093, -0.032]} scale={[1.365, 1.472, 1.397]} >
          {logoVisible && logoImage && (
            <CylindricalLogoDecal
              textureUrl={logoImage}
              labelWidth={1.3}
              labelHeight={1.3}
              labelCircumference={2.77}
              x={logoX}
              y={logoY}
              rotationY={logoRotation}
              cylindrical={cylindricalLabel}
              scale={logoScale}
            />
          )}
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
