/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spray_can.glb 
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import CylindricalLogoDecal from '@/shared/CylindricalLogoDecal';
import { useBodyMaterial } from '@/shared/useBodyMaterial';

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

const MODEL_PATH = `${basePath}/models/spray_can.glb`;

export function SprayCan({
  bodyColor,
  capColor,
  singleColorMode,
  labelImage,
  logoImage,
  brandText,
  labelVisible = true,
  logoVisible = true,
  logoX = 0,
  logoY = 0,
  logoRotation = 0,
  cylindricalLabel = true, 
  logoScale, 
  scale = 0.5,
  ...props}) {
  const { nodes, materials } = useGLTF(MODEL_PATH)

  const labelRef = useRef()
  const bodyRef = useRef()

  const bodyMaterial = useBodyMaterial(bodyColor)
  const capMaterial = useBodyMaterial(capColor);

  const labelMaterial = useMemo(() => {
    const mat = nodes.spray_can.material.clone()
    mat.transparent = true
    mat.side = THREE.DoubleSide
    mat.depthWrite = false
    mat.needsUpdate = true
    mat.opacity = 1.0
    return mat
  }, [materials])

  useEffect(() => {
    if (labelImage && labelRef.current) {
      const loader = new THREE.TextureLoader()
      loader.load(labelImage, (texture) => {
        texture.colorSpace = THREE.SRGBColorSpace
        texture.flipY = false
        texture.wrapS = texture.wrapT = THREE.RepeatWrapping
        texture.repeat.set(1, 2)
        texture.offset.set(0, 0)
        texture.needsUpdate = true

        const customMaterial = new THREE.MeshBasicMaterial({
          map: texture,
          transparent: true,
          side: THREE.DoubleSide,
          depthWrite: true,
        })
        if (labelRef.current) labelRef.current.material = customMaterial
      })
    } else if (labelRef.current) {
      labelRef.current.material = labelMaterial
    }
  }, [labelImage, labelMaterial])


  return (
    <group {...props} dispose={null}>
      <mesh ref={bodyRef} geometry={nodes.spray_can.geometry} material={bodyMaterial} position={[0, 1.992, 0]} scale={[0.683, 1.655, 0.683]} />
      <mesh geometry={nodes.cap.geometry} material={singleColorMode ? bodyMaterial : capMaterial} position={[0, 4.438, 0]} scale={[0.674, 0.602, 0.67]} />
      
      { labelVisible && (
        <mesh ref={labelRef} geometry={nodes.label.geometry} material={nodes.label.material} position={[0, 2.017, 0]} scale={[0.705, 1.746, 0.705]}>
        {logoVisible && logoImage && (
          <CylindricalLogoDecal 
            textureUrl={logoImage}
            labelWidth={1.3}
            labelHeight={1.3}
            labelCircumference={2.77}
            x={logoX}
            y={logoY}
            rotationY={logoRotation}
            cylindrical={cylindricalLabel}
            scale={logoScale}
          />
        )}
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload(MODEL_PATH)